puttingSticker/urls.py
from django.urls import path
import puttingSticker.views as sv

app_name = 'sticker'

urlpatterns = [
    path('sticker_on', sv.sticker_on, name='sticker_on'),
]

sticker/urls.py
from django.contrib import admin
from django.urls import path,include
import user.views as bv




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',bv.main,name='main'),
    path('user',include('user.urls')),
    path('user', include('puttingSticker.urls')),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
import user.views as uv

app_name='user'

urlpatterns = [
    path('main',uv.main,name='main'),
    path('login',auth_views.LoginView.as_view(template_name='mainpage.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(), name='logout'),
    path('signup',uv.signup,name='signup'),
    path('login',uv.login,name='login')

]

puttingSticker/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일 주소")

    class Meta:
        model = User
        fields=("email","username","password1","password2")

puttingSticker/views.py
from django.shortcuts import render

# Create your views here.
def sticker_on(request):
  return render(request, 'sticker/sticker_on.html')

sticker/views.py
from django.shortcuts import render

def main (request):
    return render(request,'mainpage.html')

user/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from user.forms import UserForm





def main (request):
    print(1)
    return render(request,'mainpage.html')

def signup (request):
    print(request)
    if request.method == "POST":
        form = UserForm(request.POST)
        print('hi')
        if form.is_valid():
            form.save()
            print('hi')
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            print(raw_password)
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            print(user.password)
            login(request, user)
            print(1)# 로그인
            return redirect('main')
        else:
            print(form.errors)
    else:
        form = UserForm()
        print('hi2')
    return render(request, 'user/signup.html', {'form': form})

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block extrahead %}
    {% endblock %}
    <!-- Bootstrap CSS -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- datos CSS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <style>
        .hover-effect:hover {
            transform: scale(1.05)
        }
        .main-page{
            background-image: url("{% static 'img/background2.png' %}")

        }
S

        {##main_page1{#}
        {#    background-size:cover#}

    </style>
</head>
<body style="font-family: 'Nanum Gothic', sans-serif;">
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
    <title>STICKER ON FACE</title>
    <link rel = "stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
    <body class="main-page">
    <div class="main">
        <div class="main-top">
            <div class main-desc>
                <div class="mainimg">
                    <div class="subimg" id="subimg">
                        <img src="{% static 'img/mainimg1.JPG' %}">
                        <img src="{% static 'img/mainimg2.png' %}">
                        <img src="{% static 'img/mainimg3.png' %}">
                    </div>
                        <div id = "container_wrap">
                            <div class="container" style="width: 300px;">
                            <header>
                                <a href="{% url 'user:main'  %}">
                                <img class = "brand_logo" src="{% static 'img/mainlogo2.JPG' %}" alt="logo"></a>
                            </header>
                                {% if not user.is_authenticated %}
                            <form id="login-form" name="login" action="{% url 'user:login' %}" method="post">
                                {% csrf_token %}
                                <div>
                                <label for="username"></label>
                                <input type="text" class="form-control" name="username" id="username" placeholder="id"
                                       value="{{ form.username.value|default_if_none:'' }}">
                                </div>
                                <div>
                                    <label for="password"></label>
                                    <input type="password" class="form-control" name="password" id="password" placeholder="비밀번호"
                                           value="{{ form.password.value|default_if_none:'' }}">
                                </div>
                                <button class = "loginBtn" type="submit">로그인</button>
                            </form>
                            <div class="or_line">
                                <div class="line"></div>
                                <div class="text">또는</div>
                                <div class="line"></div>
                            </div>
                            <ul class="singup">
                                <li class ='text' style="font-size: 15px; margin-left: -30px; margin-bottom: 20px;">아직 회원이 아니신가요??</li>
                                <li style="margin-left: -30px"><a href="{% url 'user:signup' %}" >가입하기</a></li>
                            </ul>
                                {% endif %}
                            </div>

                        </div>
                </div>

            </div>

        </div>

    </div>

    <script src="{% static 'js/login.js' %}"></script>
</body>


{% endblock %}

templates/navbar.html
{% load static %}<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <img style="width: 80px"   src="{% static 'img/mainlogo1.JPG' %}" alt="logo">
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'user:logout' %}">{{ user.username }} (로그아웃)</a></li>
                       <li><a class="nav-link" href="#">나만의 저장소</a></li>
                        <a class="nav-link" href="{% url 'user:main' %}">🏚️(HOME)</a>
                    {% else %}
                    <a class="nav-link" href="#"></a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                     <a class="nav-link" href="{% url 'user:main' %}">🏚️(HOME)</a>

                    {% endif %}
                </li>
                <li>
                    <a class="nav-link" href="#"></a>
                </li>
                <li>
                    <a class="nav-link" href="#"></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/sticker/sticker_on.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>hi</h1>
</body>
</html>

templates/user/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
    <title>SIGN-UP</title>
    <link rel = "stylesheet" href="{% static 'css/signup.css' %}">
    </head>
    <body class="main-page" style="background-size: cover">
    <div class="join_container">
            <header class = "logo">
                <img class = "brand_logo" style="width: 100px" src="{% static 'img/mainlogo2.JPG' %}" alt="logo">
                <ul>
                    <li>당신의 사진을 꾸미고 싶으면</li>
                    <li> 가입하세요.</li>
                </ul>
            </header>
            <div class="or_line">
                <div class="line"></div>
                <div class="text">⬇⬇⬇</div>
                <div class="line"></div>
            </div>
                <form name="join" action="{% url 'user:signup' %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <div>
                        <label for="username"></label>
                        <input class = "name"  name="username" type="text" id="username" placeholder="ID">
                    </div>
                        <label for="email"></label>
                        <input class = "addEmail" type="text" name="email" id="email" placeholder="이메일 주소"
                               value="{{ form.email.value|default_if_none:'' }}">
                    </div>
                    <div>
                    <label for="password1"></label>
                    <input class = "id" name="password1" type="password" id="password1" placeholder="비밀번호"
                    value="{{ form.password1.value|default_if_none:'' }}">
                      </div>
                     <div>
                    <label for="password2"></label>
                    <input class = "pw" name="password2" type="password" id="password2" placeholder="비밀번호 확인"
                           value="{{ form.password2.value|default_if_none:'' }}">
                      </div>
                    <button class = "joinBtn" type="submit">가입</button>
                </form>
    </div>



        <script src="{% static 'js/signup.js' %}"></script>
</body>



{% endblock %}